apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-db-operator
  namespace: homework
  labels:
    app: custom-db-operator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: "custom-db-resource"
  template:
    metadata:
      labels:
        app: "custom-db-resource"
    spec:
      serviceAccountName: custom-op
      containers:
        - name: mysql-operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          imagePullPolicy: IfNotPresent
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "1000m"
