apiVersion: v1
kind: Service
metadata:
  namespace: { { .Values.namespace } }
  labels:
    app: { { .Values.webServexService.name } }
  name: { { .Values.webServerService.name } }
spec:
  ports:
    - name: { { .Values.webServerService.name } }
      port: { { .Values.webServerService.port } }
      protocol: { { .Values.webServerService.protocol } }
      targetPort: { { .Values.webServerService.targetPort } }
  selector:
    app: { { .Values.webServerService.appSelector } }
  type: ClusterIP
