apiVersion: v1
kind: Service
metadata:
  name: { { include "hwChart.name" . } }
  labels: &labels { { - include "hwChart.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  selector: *labels
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      name: { { .Values.service.portName } }
