---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: { { .Values.persistentVolume.name } }
  namespace: { { .Values.namespace } }
spec:
  capacity:
    storage: { { .Values.persistentVolume.StorageCapacity } }
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: { { .Values.persistentVolume.ReclaimPolicy } }
  hostPath:
    path: "/tmp/data/"
  claimRef:
    name: { { .Values.persistentVolume.ClaimRefName } }
    namespace: { { .Values.namespace } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { .Values.persistenVolumeClaim.name } }
  namespace: { { .Values.namespace } }
spec:
  volumeName: { { .Values.persistenVolumeClaim.volumeName } }
  accessModes:
    - { { .Values.persistentVolumeClaim.accessModes } }
  storageClassName: { { .Values.persistentVolumeClaim.storageClassName } }
  resources:
    requests:
      storage: { { .Values.persistVolumeClaim.storageSize } }
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storage-class
  namespace: homework
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"

provisioner: kubernetes.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true"
