apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cd-roles-bindings.yaml
  - cm.yaml
  - deployment.yaml
  - ingress.yaml
  - monitoring-roles-bindings.yaml
  - namespace.yaml
  - service.yaml
  - storage.yaml
  - cd-config-secret.yaml
