# Default values for hwChart.

##########################################
# Deployment
##########################################
replicaCount: 1

image:
  name: joseluisq/static-web-server:2
  repository: nginx
  tag: 2
  imagePullPolicy: IfNotPresent
enableReadinessProbe: true

##########################################
# Service
##########################################
service:
  type: ClusterIP
  port: 80
  portName: webserver
