apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: static-web-server
  name: static-web-server
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-web-server
  strategy: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homework
    spec:
      containers:
        - image: joseluisq/static-web-server:2
          name: static-beb-server
          env:
            - name: SERVER_ROOT
              value: "/homework"
            - name: SERVER_PORT
              value: "8000"
          lifecycle:
            preStop:
              exec:
              command: ["/bin/sh", "-c", "rm  /homework/index.html"]
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", " cat /homework/index.html"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /homework
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: homework
                    operator: In
                    values:
                      - "true"
      initContainers:
        - name: init-container
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "echo '<!DOCTYPE html><html><body><h1>My First Heading</h1><p>My first paragraph.</p></body></html>' > /init/index.html",
            ]
          restartPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /init
      volumes:
        - name: data
          emptyDir: {}
