apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-pvc
  namespace: homework
spec:
  volumeName: hw-pv
  accessModes:
    - ReadWriteMany
  storageClassName: custom-storage-class
  resources:
    requests:
      storage: 250Mi
