apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storage-class
  namespace: homework
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true"
